##docker-compose.yml

neo4j:
    image: neo4j:4.0          ## we use neo4j v4
    ports:                    ## publish ports to have Web UI
     - "17474:7474"
    volumes:                  ## adds folder with login/password
     - ./db/dbms:/data/dbms